### ISSUE TITLE
Rename to wikimedia-pageviews

### ISSUE THREAD

**Issue by yuvipanda** [milimetric/wmf#1]
And maybe move to github.com/mediawiki-utilities? :D Having this be another library that fits into the larger group of libraries doing a single specific thing would be awesomer than trying to be 'be all end all'.

AWESOME OTHERWISE.

**Comment by milimetric** [comment]
I kinda wanted to move it in there, but I felt like mediawiki purists would get upset if I brought wikimedia specific stuff in.  I also thought of renaming it wikimedia-pageviews but then I kind of wanted it to be more general purpose 'cause we'll add more APIs later on like edit data, etc.  So I like the wmf.analytics.api structure.  But I only self-bike-shedded on it for like 30 minutes, definitely could use more bike shedding.

**Comment by yuvipanda** [comment]
It already has python-mwmetrics (which is more wikimedia metrics), so I think it'll fit in there. If you want it to be more generic, maybe wikimedia-analytics-client? (wac?)

**Comment by yuvipanda** [comment]
I guess I just feel like a name should be at least vaguely self-descriptive, and 'wmf' isn't...

**Comment by legoktm** [comment]
Is the pageviews API actually Wikimedia specific? (I have no idea, I thought it was just something that integrated with restbase)

With mediawiki-utilities we've been moving in the direction of distinct libraries that do one thing, and all work together. It's still possible to use a "wmf.analytics.api" structure across multiple libraries if you really want. (But that really should be "wikimedia" and not "wmf".) So +1 to "wikimedia-pageviews" or something like that.

**Comment by milimetric** [comment]
pageview API is Wikimedia specific, yes.  But hey, if we've got other wikimedia specific stuff in mediawiki-utilities, let's merge this in there!!  I don't want my own repo, that sucks and I'm lazy.  Where do you think this would fit best in mediawiki-utilities?  mw/analytics/api ?  I could care less about the naming here, you tell me where to put it and I'll PR.

**Comment by milimetric** [comment]
Moved to https://github.com/mediawiki-utilities/python-mwviews.  Thanks!
